language: java

git:
  depth: false

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - TEST_MILL_VERSION=
  - TEST_MILL_VERSION=0.3.6-25-b553df

script:
  - ./millw -i version
  - ./mill -i test
