language: scala

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - MILL_VERSION=0.3.6
  - MILL_VERSION=0.3.6
    TEST_MILL_VERSION=0.3.6-25-b553df

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION} && chmod +x ~/bin/mill
  # If TEST_MILL_VERSION defined, we also download that version as ~/bin/mill-test
  - if [ "x$TEST_MILL_VERSION" != "x" ] ; then curl -L -o ~/bin/mill-test https://github.com/lihaoyi/mill/releases/download/${TEST_MILL_VERSION}/${TEST_MILL_VERSION} && chmod +x ~/bin/mill-test ; else ln -s ~/bin/mill ~/bin/mill-test ; fi
  - export PATH=~/bin/mill:$PATH
  - mill -i test
  - mill -i test $HOME/bin/mill-test
