language: java

git:
  depth: false

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - TEST_MILL_VERSION=
  - TEST_MILL_VERSION=0.3.8
  - TEST_MILL_VERSION=0.4.0
  - TEST_MILL_VERSION=0.4.1
  - TEST_MILL_VERSION=0.4.2
  - TEST_MILL_VERSION=0.5.0
  - TEST_MILL_VERSION=0.5.1
  - TEST_MILL_VERSION=0.5.2
  - TEST_MILL_VERSION=0.5.3

script:
  - ./millw -i version
  - ./millw -i test
