language: java

git:
  depth: false

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - TEST_MILL_VERSION=
  - TEST_MILL_VERSION=0.5.7

script:
  - ./millw -i version
  - ./millw -i test
