language: scala

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

env:
  - MILL_VERSION=0.2.8
  - MILL_VERSION=0.3.4
  - MILL_VERSION=0.3.5

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION} && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill _test
