on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build"
        run: ./millw -j 0 __.publishLocal $(pwd)/testRepo
      - name: "Test"
        run: ./millw -j 0 -k __.testCached

